[build]
functions = "./functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

[build.environment]
  MONGO_URI = "mongodb+srv://expense-tracker:Ls94f0gBap8PcRmr@cluster0.likmj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

